version: '3'
services:
    db:
        platform: linux/x86_64
        image: mysql:8.0.19
        ports:
            - 3306:3306
        container_name: book-db
        environment:
            - MYSQL_DATABASE=book-manager
            - MYSQL_USER=okarin
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
            - TZ="Asia/Tokyo"
